export default {
  CREATE_USER_ACTION: 'CREATE_USER_ACTION',
  LOGIN_USER_ACTION: 'LOGIN_USER_ACTION',
  USER_LOGOUT: "USER_LOGOUT",

  USERS_REQUEST: 'USERS_REQUEST',
  USERS_RESPONSE: 'USERS_RESPONSE',
  USERS_ERROR: 'USERS_ERROR',

  TOKENS_ACTION_WITH_LOCAL: "TOKENS_ACTION_WITH_LOCAL",
  TOKENS_ERROR: "TOKENS_ERROR",

  GET_USER_ACTION: "GET_USER_ACTION",

  GET_ALL_USERS: "GET_ALL_USERS",
  BAN_USER_BY_ID: "BAN_USER_BY_ID",

  CREATE_CONTEST_ACTION: "CREATE_CONTEST_ACTION",
  NEXT_STAGE_CONTEST: "NEXT_STAGE_CONTEST",
  PREV_STAGE_CONTEST: "PREV_STAGE_CONTEST",
  STAGE_CONTEST: "STAGE_CONTEST",

  TO_CONTEST_QUEUE: "TO_CONTEST_QUEUE",
};
