export default {
  USERS_REQUEST: 'USERS_REQUEST',
  USERS_RESPONSE: 'USERS_RESPONSE',
  USERS_ERROR: 'USERS_ERROR',
  
  CREATE_USER: 'CREATE_USER',
  GET_USER: "GET_USER",
  LOGIN_USER: 'LOGIN_USER',
  USER_LOGOUT: "USER_LOGOUT",

  GET_ALL_USER: "GET_ALL_USERS",
  BAN_USER_BY_ID: "BAN_USER_BY_ID",


  SAVE_TOKENS_LOCALLY: "SAVE_TOKENS_LOCALLY",
  TOKENS_ERROR: "TOKENS_ERROR",
};
